version: '3.0'
services:
  #5.6
  php:
    build: ./php
    ports:
        - 9008:9000
    volumes:
        - ./php/php-fpm.d/:/etc/php-fpm.d/
        - ./www/:/www/
        - ./www_test/:/www_test/

  #7.2
  php7:
    build: ./php7
    depends_on:
        - mysql
    ports:
        - 9078:9001
    volumes:
        - ./php/php-fpm.d/:/etc/php-fpm.d/
        - ./www/:/www/
        - ./www_test/:/www_test/
    links:
        - mysql:mysql

  nginx:
    build: ./nginx
    depends_on:
        - php
        - php7
    ports:
        - 80:80
        - 443:443
    volumes:
        - ./nginx/conf.d/:/etc/nginx/conf.d/
        - ./nginx/log/:/var/log/nginx/
        - ./www/:/www/
        - ./www_test/:/www_test/
    links:
        - php:php
        - php7:php7
    #extra_hosts:
    #    - dockerhost:$DOCKERHOST
  #5.6
  mysql:
    build: ./mysql
    ports:
        - 3308:3306
    volumes:
        - ./mysql/data/:/var/lib/mysql/
    environment:
        MYSQL_ROOT_PASSWORD: ibaotu

  redis:
      build: ./redis

      ports:
        - 6378:6379
      volumes:
        - ./redis/data:/data
